// Copyright 2017-2022 Parity Technologies (UK) Ltd.
// This file is part of Polkadot.

// Polkadot is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Polkadot is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Polkadot.  If not, see <http://www.gnu.org/licenses/>.
//! Autogenerated weights for `pallet_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
<<<<<<< HEAD
//! DATE: 2022-04-20, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
=======
//! DATE: 2022-03-15, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("polkadot-dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/polkadot
// benchmark
// pallet
// --chain=polkadot-dev
// --steps=50
// --repeat=20
// --pallet=pallet_identity
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./file_header.txt
// --output=./runtime/polkadot/src/weights/pallet_identity.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_identity`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_identity::WeightInfo for WeightInfo<T> {
	// Storage: Identity Registrars (r:1 w:1)
	fn add_registrar(r: u32, ) -> Weight {
<<<<<<< HEAD
		(11_894_000 as Weight)
			// Standard Error: 3_000
			.saturating_add((197_000 as Weight).saturating_mul(r as Weight))
=======
		(11_921_000 as Weight)
			// Standard Error: 4_000
			.saturating_add((218_000 as Weight).saturating_mul(r as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Identity IdentityOf (r:1 w:1)
	fn set_identity(r: u32, x: u32, ) -> Weight {
<<<<<<< HEAD
		(25_963_000 as Weight)
			// Standard Error: 8_000
			.saturating_add((157_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 1_000
			.saturating_add((367_000 as Weight).saturating_mul(x as Weight))
=======
		(24_706_000 as Weight)
			// Standard Error: 7_000
			.saturating_add((196_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 1_000
			.saturating_add((370_000 as Weight).saturating_mul(x as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Identity IdentityOf (r:1 w:0)
	// Storage: Identity SubsOf (r:1 w:1)
	// Storage: Identity SuperOf (r:1 w:1)
	fn set_subs_new(s: u32, ) -> Weight {
<<<<<<< HEAD
		(22_454_000 as Weight)
=======
		(22_430_000 as Weight)
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			// Standard Error: 1_000
			.saturating_add((2_651_000 as Weight).saturating_mul(s as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(s as Weight)))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(s as Weight)))
	}
	// Storage: Identity IdentityOf (r:1 w:0)
	// Storage: Identity SubsOf (r:1 w:1)
	// Storage: Identity SuperOf (r:0 w:1)
	fn set_subs_old(p: u32, ) -> Weight {
<<<<<<< HEAD
		(21_790_000 as Weight)
			// Standard Error: 0
			.saturating_add((755_000 as Weight).saturating_mul(p as Weight))
=======
		(21_791_000 as Weight)
			// Standard Error: 0
			.saturating_add((740_000 as Weight).saturating_mul(p as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(p as Weight)))
	}
	// Storage: Identity SubsOf (r:1 w:1)
	// Storage: Identity IdentityOf (r:1 w:1)
	// Storage: Identity SuperOf (r:0 w:100)
	fn clear_identity(r: u32, s: u32, x: u32, ) -> Weight {
<<<<<<< HEAD
		(27_543_000 as Weight)
			// Standard Error: 4_000
			.saturating_add((103_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 0
			.saturating_add((741_000 as Weight).saturating_mul(s as Weight))
			// Standard Error: 0
			.saturating_add((229_000 as Weight).saturating_mul(x as Weight))
=======
		(28_075_000 as Weight)
			// Standard Error: 4_000
			.saturating_add((75_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 0
			.saturating_add((723_000 as Weight).saturating_mul(s as Weight))
			// Standard Error: 0
			.saturating_add((230_000 as Weight).saturating_mul(x as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(s as Weight)))
	}
	// Storage: Identity Registrars (r:1 w:0)
	// Storage: Identity IdentityOf (r:1 w:1)
	fn request_judgement(r: u32, x: u32, ) -> Weight {
<<<<<<< HEAD
		(26_600_000 as Weight)
			// Standard Error: 5_000
			.saturating_add((200_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 0
			.saturating_add((431_000 as Weight).saturating_mul(x as Weight))
=======
		(26_859_000 as Weight)
			// Standard Error: 4_000
			.saturating_add((187_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 0
			.saturating_add((429_000 as Weight).saturating_mul(x as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Identity IdentityOf (r:1 w:1)
	fn cancel_request(r: u32, x: u32, ) -> Weight {
<<<<<<< HEAD
		(23_715_000 as Weight)
			// Standard Error: 6_000
			.saturating_add((167_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 0
			.saturating_add((423_000 as Weight).saturating_mul(x as Weight))
=======
		(23_991_000 as Weight)
			// Standard Error: 7_000
			.saturating_add((149_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 1_000
			.saturating_add((419_000 as Weight).saturating_mul(x as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Identity Registrars (r:1 w:1)
	fn set_fee(r: u32, ) -> Weight {
<<<<<<< HEAD
		(4_523_000 as Weight)
			// Standard Error: 2_000
			.saturating_add((160_000 as Weight).saturating_mul(r as Weight))
=======
		(4_606_000 as Weight)
			// Standard Error: 2_000
			.saturating_add((165_000 as Weight).saturating_mul(r as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Identity Registrars (r:1 w:1)
	fn set_account_id(r: u32, ) -> Weight {
<<<<<<< HEAD
		(4_176_000 as Weight)
			// Standard Error: 1_000
			.saturating_add((157_000 as Weight).saturating_mul(r as Weight))
=======
		(4_458_000 as Weight)
			// Standard Error: 2_000
			.saturating_add((167_000 as Weight).saturating_mul(r as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Identity Registrars (r:1 w:1)
	fn set_fields(r: u32, ) -> Weight {
<<<<<<< HEAD
		(4_546_000 as Weight)
			// Standard Error: 2_000
			.saturating_add((152_000 as Weight).saturating_mul(r as Weight))
=======
		(4_723_000 as Weight)
			// Standard Error: 2_000
			.saturating_add((163_000 as Weight).saturating_mul(r as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Identity Registrars (r:1 w:0)
	// Storage: Identity IdentityOf (r:1 w:1)
	fn provide_judgement(r: u32, x: u32, ) -> Weight {
<<<<<<< HEAD
		(18_560_000 as Weight)
			// Standard Error: 6_000
			.saturating_add((144_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 0
			.saturating_add((422_000 as Weight).saturating_mul(x as Weight))
=======
		(18_391_000 as Weight)
			// Standard Error: 5_000
			.saturating_add((153_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 0
			.saturating_add((426_000 as Weight).saturating_mul(x as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Identity SubsOf (r:1 w:1)
	// Storage: Identity IdentityOf (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Identity SuperOf (r:0 w:100)
	fn kill_identity(r: u32, s: u32, x: u32, ) -> Weight {
<<<<<<< HEAD
		(41_346_000 as Weight)
			// Standard Error: 12_000
			.saturating_add((64_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 1_000
			.saturating_add((744_000 as Weight).saturating_mul(s as Weight))
			// Standard Error: 1_000
			.saturating_add((6_000 as Weight).saturating_mul(x as Weight))
=======
		(40_194_000 as Weight)
			// Standard Error: 4_000
			.saturating_add((49_000 as Weight).saturating_mul(r as Weight))
			// Standard Error: 0
			.saturating_add((726_000 as Weight).saturating_mul(s as Weight))
			// Standard Error: 0
			.saturating_add((7_000 as Weight).saturating_mul(x as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(s as Weight)))
	}
	// Storage: Identity IdentityOf (r:1 w:0)
	// Storage: Identity SuperOf (r:1 w:1)
	// Storage: Identity SubsOf (r:1 w:1)
	fn add_sub(s: u32, ) -> Weight {
<<<<<<< HEAD
		(29_453_000 as Weight)
			// Standard Error: 0
			.saturating_add((104_000 as Weight).saturating_mul(s as Weight))
=======
		(28_585_000 as Weight)
			// Standard Error: 0
			.saturating_add((115_000 as Weight).saturating_mul(s as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Identity IdentityOf (r:1 w:0)
	// Storage: Identity SuperOf (r:1 w:1)
	fn rename_sub(s: u32, ) -> Weight {
<<<<<<< HEAD
		(8_899_000 as Weight)
			// Standard Error: 0
			.saturating_add((20_000 as Weight).saturating_mul(s as Weight))
=======
		(9_134_000 as Weight)
			// Standard Error: 0
			.saturating_add((19_000 as Weight).saturating_mul(s as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Identity IdentityOf (r:1 w:0)
	// Storage: Identity SuperOf (r:1 w:1)
	// Storage: Identity SubsOf (r:1 w:1)
	fn remove_sub(s: u32, ) -> Weight {
<<<<<<< HEAD
		(30_251_000 as Weight)
			// Standard Error: 0
			.saturating_add((94_000 as Weight).saturating_mul(s as Weight))
=======
		(30_580_000 as Weight)
			// Standard Error: 2_000
			.saturating_add((83_000 as Weight).saturating_mul(s as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Identity SuperOf (r:1 w:1)
	// Storage: Identity SubsOf (r:1 w:1)
	fn quit_sub(s: u32, ) -> Weight {
<<<<<<< HEAD
		(19_592_000 as Weight)
			// Standard Error: 0
			.saturating_add((93_000 as Weight).saturating_mul(s as Weight))
=======
		(19_427_000 as Weight)
			// Standard Error: 0
			.saturating_add((97_000 as Weight).saturating_mul(s as Weight))
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}
