[package]
name = "polkadot-node-jaeger"
<<<<<<< HEAD
version = "0.9.19"
=======
version = "0.9.18"
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Polkadot Jaeger primitives, but equally useful for Grafana/Tempo"

[dependencies]
async-std = "1.11.0"
mick-jaeger = "0.1.8"
lazy_static = "1.4"
parking_lot = "0.12.0"
polkadot-primitives = { path = "../../primitives" }
polkadot-node-primitives = { path = "../primitives" }
<<<<<<< HEAD
sc-network = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
thiserror = "1.0.31"
log = "0.4.17"
parity-scale-codec = { version = "3.1.2", default-features = false }
=======
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
thiserror = "1.0.30"
log = "0.4.13"
parity-scale-codec = { version = "3.0.0", default-features = false }
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
