[package]
name = "polkadot-node-subsystem"
<<<<<<< HEAD
version = "0.9.19"
=======
version = "0.9.18"
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Subsystem traits and message definitions and the generated overseer"

[dependencies]
polkadot-overseer = { path = "../overseer" }
polkadot-node-subsystem-types = { path = "../subsystem-types" }
polkadot-node-jaeger = { path = "../jaeger" }
