[package]
name = "erasure_coding_fuzzer"
<<<<<<< HEAD
version = "0.9.19"
=======
version = "0.9.18"
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
polkadot-erasure-coding = { path = ".." }
honggfuzz = "0.5"
primitives = { package = "polkadot-node-primitives", path = "../../node/primitives/" }

[[bin]]
name = "reconstruct"
path = "src/reconstruct.rs"

[[bin]]
name = "round_trip"
path = "src/round_trip.rs"

[workspace]
