[package]
name = "staking-miner"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
tokio = { version = "1.14", features = ["macros"] }
log = "0.4.11"
env_logger = "0.9.0"
structopt = "0.3.25"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", rev = "0e46b5cea9cd632dc438a005c77bbaa5c2af562f", features = ["ws-client"] }
serde_json = "1.0"
serde = "1.0.130"
paste = "1.0.6"
thiserror = "1.0.30"

remote-externalities = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
sp-npos-elections = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }


frame-system = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
frame-election-provider-support = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
pallet-election-provider-multi-phase = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }

core-primitives = { package = "polkadot-core-primitives", path = "../../core-primitives" }

runtime-common = { package = "polkadot-runtime-common", path = "../../runtime/common" }
polkadot-runtime = { path = "../../runtime/polkadot" }
kusama-runtime = { path = "../../runtime/kusama" }
westend-runtime = { path = "../../runtime/westend" }

sub-tokens = { git = "https://github.com/paritytech/substrate-debug-kit", branch = "master" }

[dev-dependencies]
sp-version = { git = "https://github.com/paritytech/substrate", branch = "dp-jsonrpsee-integration-2" }
