[package]
name = "backchannel-cli"
version = "0.1.0"
edition = "2021"

[package]
name = "zombienet-backchannel"
description = "Zombienet backchannel to notify test runner and coordinate with malus actors."
license = "GPL-3.0-only"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
readme = "README.md"
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# futures-channel = "0.3"
tokio = { version = "1.0.0", default-features = false, features = ["macros", "net", "rt-multi-thread"] }
url = "2.0.0"
tokio-tungstenite = "0.16"
futures-util = "0.3.18"
parity-scale-codec = { version = "2.3.1", features = ["derive"] }
reqwest = "0.11"
thiserror = "1.0.30"
log = "0.4.13"
