[package]
name = "remote-ext-tests-bags-list"
<<<<<<< HEAD
version = "0.9.19"
=======
version = "0.9.18"
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
<<<<<<< HEAD
polkadot-runtime = { path = "../../../runtime/polkadot" }
kusama-runtime = { path = "../../../runtime/kusama" }
westend-runtime = { path = "../../../runtime/westend" }
polkadot-runtime-constants = { path = "../../../runtime/polkadot/constants" }
kusama-runtime-constants = { path = "../../../runtime/kusama/constants" }
westend-runtime-constants = { path = "../../../runtime/westend/constants" }
=======
polkadot-runtime = { version = "0.9.18", path = "../../../runtime/polkadot" }
kusama-runtime = { version = "0.9.18", path = "../../../runtime/kusama" }
westend-runtime = { version = "0.9.18", path = "../../../runtime/westend" }
polkadot-runtime-constants = { version = "0.9.18", path = "../../../runtime/polkadot/constants" }
kusama-runtime-constants = { version = "0.9.18", path = "../../../runtime/kusama/constants" }
westend-runtime-constants = { version = "0.9.18", path = "../../../runtime/westend/constants" }
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111

pallet-bags-list-remote-tests = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }

clap = { version = "3.1", features = ["derive"] }
log = "0.4.17"
tokio = { version = "1.18.1", features = ["macros"] }
