[package]
name = "polkadot-node-network-protocol"
<<<<<<< HEAD
version = "0.9.19"
=======
version = "0.9.18"
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Primitives types for the Node-side"

[dependencies]
async-trait = "0.1.53"
polkadot-primitives = { path = "../../../primitives" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-jaeger = { path = "../../jaeger" }
<<<<<<< HEAD
parity-scale-codec = { version = "3.1.2", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "master" }
=======
parity-scale-codec = { version = "3.0.0", default-features = false, features = ["derive"] }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
>>>>>>> 9ed0c98204d25eaad8a6b40248daee8e6a40d111
strum = { version = "0.24", features = ["derive"] }
futures = "0.3.21"
thiserror = "1.0.31"
fatality = "0.0.6"
rand = "0.8"
derive_more = "0.99"

[dev-dependencies]
rand_chacha = "0.3.1"
